### ISSUE TITLE
SPI code needs to be changed for Arduboy2 V4.0.0

### ISSUE THREAD

**Issue by MLXXXp** [Joshimuz/TheBounceArduboy#1]
Arduboy2 library version 4.0.0 no longer uses the Arduino SPI library, so _SPI.h_ is no longer included when a sketch includes _Arduboy2.h_

This sketch uses SPI functions, so it fails to compile with the latest Arduboy2 library.

To fix this, in file _TheBounceArduboy.ino_ replace all instances of

`SPI.transfer(`

with

`arduboy.SPItransfer(`

**Comment by Joshimuz** [comment]
Done, thanks!
